name: Deploy
on:
  workflow_dispatch:
    inputs:
      deployChannels:
        description: 'Channels to deploy'
        required: true

jobs:
  deploy_webhooks:
    name: Build and deploy webhooks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node v16
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn install

      - name: Build code
        run: yarn build

      - name: Run deploy code
        run: yarn deploy
        env:
          RESOURCES: https://discord.com/api/webhooks/${{ secrets.WEBHOOK_RESOURCES_ID }}/${{ secrets.WEBHOOK_RESOURCES_TOKEN }}
          RULES: https://discord.com/api/webhooks/${{ secrets.WEBHOOK_RULES_ID }}/${{ secrets.WEBHOOK_RULES_TOKEN }}
          ROLES: https://discord.com/api/webhooks/${{ secrets.WEBHOOK_ROLES}}/${{ secrets.WEBHOOK_ROLES_TOKEN }}
          FAQ: https://discord.com/api/webhooks/${{ secrets.WEBHOOK_FAQ}}/${{ secrets.WEBHOOK_FAQ }}
          WEBHOOK_AVATAR: ${{ secrets.WEBHOOK_AVATAR }}
          WEBHOOK_NAME: ${{ secrets.WEBHOOK_NAME }}
          DEPLOY_CHANNELS: ${{ github.event.inputs.deployChannels }}
